/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tables to Genies API
 * API for creating Genie rooms from UC tables
 * OpenAPI spec version: 1.0.0
 */
export type CatalogOutComment = string | null;

export type CatalogOutOwner = string | null;

/**
 * Catalog output model.
 */
export interface CatalogOut {
  name: string;
  comment?: CatalogOutComment;
  owner?: CatalogOutOwner;
}

/**
 * Enriched column model.
 */
export interface ColumnEnriched {
  name: string;
  type: string;
  comment: string;
  sample_values: string[];
}

export type ColumnOutComment = string | null;

/**
 * Column output model.
 */
export interface ColumnOut {
  name: string;
  type_text: string;
  type_name: string;
  comment?: ColumnOutComment;
  nullable: boolean;
  position: number;
}

/**
 * Created Genie room with URL.
 */
export interface CreatedGenieRoomOut {
  id: string;
  name: string;
  space_id: string;
  url: string;
  table_count: number;
  status: GenieRoomStatus;
}

/**
 * Response when submitting enrichment job.
 */
export interface EnrichmentJobOut {
  run_id: number;
  job_url: string;
  status: EnrichmentStatus;
  table_count: number;
  submitted_at: string;
}

export type EnrichmentJobStatusOutLifeCycleState = string | null;

export type EnrichmentJobStatusOutResultState = string | null;

export type EnrichmentJobStatusOutStateMessage = string | null;

export type EnrichmentJobStatusOutStartTime = number | null;

export type EnrichmentJobStatusOutEndTime = number | null;

export type EnrichmentJobStatusOutDurationMs = number | null;

/**
 * Job status response.
 */
export interface EnrichmentJobStatusOut {
  run_id: number;
  status: EnrichmentStatus;
  job_url: string;
  life_cycle_state?: EnrichmentJobStatusOutLifeCycleState;
  result_state?: EnrichmentJobStatusOutResultState;
  state_message?: EnrichmentJobStatusOutStateMessage;
  start_time?: EnrichmentJobStatusOutStartTime;
  end_time?: EnrichmentJobStatusOutEndTime;
  duration_ms?: EnrichmentJobStatusOutDurationMs;
}

/**
 * Summary enrichment result.
 */
export interface EnrichmentResultListOut {
  fqn: string;
  column_count: number;
  enriched: boolean;
}

/**
 * Full enrichment result for a table.
 */
export interface EnrichmentResultOut {
  fqn: string;
  catalog: string;
  schema: string;
  table: string;
  column_count: number;
  columns: ColumnEnriched[];
  enriched: boolean;
  timestamp: string;
}

/**
 * Input for running enrichment.
 */
export interface EnrichmentRunIn {
  table_fqns: string[];
}

/**
 * Enrichment job status.
 */
export type EnrichmentStatus = typeof EnrichmentStatus[keyof typeof EnrichmentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnrichmentStatus = {
  pending: 'pending',
  running: 'running',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

export type GenieCreationStatusOutRoomsItem = { [key: string]: unknown };

/**
 * Status of Genie room creation process.
 */
export interface GenieCreationStatusOut {
  status: string;
  rooms: GenieCreationStatusOutRoomsItem[];
}

/**
 * Input for creating a Genie room definition.
 */
export interface GenieRoomIn {
  /** @minLength 1 */
  name: string;
  /** @minItems 1 */
  table_fqns: string[];
}

/**
 * Summary Genie room for lists.
 */
export interface GenieRoomListOut {
  id: string;
  name: string;
  table_count: number;
}

/**
 * Full Genie room output.
 */
export interface GenieRoomOut {
  id: string;
  name: string;
  tables: string[];
  table_count: number;
}

/**
 * Genie room status.
 */
export type GenieRoomStatus = typeof GenieRoomStatus[keyof typeof GenieRoomStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GenieRoomStatus = {
  pending: 'pending',
  creating: 'creating',
  created: 'created',
  failed: 'failed',
} as const;

/**
 * Graph build status.
 */
export type GraphBuildStatus = typeof GraphBuildStatus[keyof typeof GraphBuildStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GraphBuildStatus = {
  pending: 'pending',
  building: 'building',
  completed: 'completed',
  failed: 'failed',
} as const;

export type GraphBuildStatusOutError = string | null;

/**
 * Graph build status.
 */
export interface GraphBuildStatusOut {
  job_id: string;
  status: GraphBuildStatus;
  error?: GraphBuildStatusOutError;
}

export type GraphDataOutElementsItem = { [key: string]: unknown };

export type GraphDataOutCommunitiesAnyOf = { [key: string]: unknown };

export type GraphDataOutCommunities = GraphDataOutCommunitiesAnyOf | null;

/**
 * Full graph data.
 */
export interface GraphDataOut {
  elements: GraphDataOutElementsItem[];
  node_count: number;
  edge_count: number;
  communities?: GraphDataOutCommunities;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type SchemaOutComment = string | null;

export type SchemaOutOwner = string | null;

/**
 * Schema output model.
 */
export interface SchemaOut {
  name: string;
  catalog_name: string;
  comment?: SchemaOutComment;
  owner?: SchemaOutOwner;
}

export type TableOutComment = string | null;

export type TableOutOwner = string | null;

/**
 * Table output model.
 */
export interface TableOut {
  name: string;
  catalog_name: string;
  schema_name: string;
  table_type: string;
  comment?: TableOutComment;
  owner?: TableOutOwner;
  fqn: string;
}

/**
 * Input for saving table selection.
 */
export interface TableSelectionIn {
  table_fqns: string[];
}

/**
 * Table selection output.
 */
export interface TableSelectionOut {
  table_fqns: string[];
  count: number;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

